### PR TITLE
feature: eslint added and fixed a few eslint errors

### LINKED ISSUE #117: Add eslint
For frontend, we can use https://github.com/joeldenning/eslint-config-react-important-stuff. For backend we can maybe reuse the same config, or use https://github.com/joeldenning/eslint-config-node-important-stuff

### PR DESCRIPTION
**Pull request by scotttball**
Closes #117 

* added eslint
* added `joeldenning/eslint-config-react-important-stuff`
* fixed up .eslintrc
* husky/lint-staged for frontend
* added `yarn lint`

_currently only eslint for frontend (need to configure for ejs and node to further checks for backend)_

### CODE REVIEW

**Comment by scotttball** [comment]
I still need to do some manual testing on this. I've had issues with some other projects with eslint rules and hooks. I've ran into some infinite rendering issues with the props that eslint recommends to observe. Sometimes it's not always correct. I'll check it out tomorrow. 

Please comment if there are any changes that should be made to this PR.

File: frontend/app/forms/inputs/text-area.component.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ export default function TextArea(props) {
 
   React.useEffect(() => {
     setValue(get(dataContext.data, props.dataKey, ""));
-  }, [dataContext]);
+  }, [dataContext, props.dataKey]);
```
Comment (joeldenning) [inline frontend/app/forms/inputs/text-area.component.js]: Wow yes all these effect dependency array errors is a great reason why we should have had linting all along

File: frontend/app/overview/vocabulary/defined-term.component.js [hunk 2]
```diff
@@ -10,7 +10,26 @@ export default function DefinedTerm(props) {
   const containerRef = useRef(null);
   const alwaysLink =
     useContext(DefinedTermContext).alwaysLink || props.alwaysLink;
+
+  const openTooltip = () => {
```
Comment (joeldenning) [inline frontend/app/overview/vocabulary/defined-term.component.js]: Why did these functions get moved, and why switched to consts + arrow function?

File: frontend/app/user/cases-list.component.js [hunk 3]
```diff
@@ -35,6 +35,7 @@ export default class CasesList extends React.Component {
                     </button>
                   )}
                   <button className="danger small">Delete</button>
+                  {/* delete currently does nothing? */}
```
Comment (joeldenning) [inline frontend/app/user/cases-list.component.js]: Ha good point, yeah we should fix that.

File: frontend/app/utils/accordion.component.js [hunk 4]
```diff
@@ -30,14 +30,16 @@ export default class Accordion extends React.Component {
 
             return (
               <div key={index}>
-                <a
+                <div
```
Comment (joeldenning) [inline frontend/app/utils/accordion.component.js]: Might be better to use `<button className="unstyled">`. It's easier to get accessibility right by using `<button>` than by `<div role="button">`

See https://github.com/JustUtahCoders/utahexpungements.org/blob/92ec0e5ca1433231e0d46037175031192d4942eb/frontend/styleguide.js#L146

Comment (scotttball) [reply frontend/app/utils/accordion.component.js]: Agreed! I’ll make the change later today.

File: frontend/app/overview/vocabulary/defined-term.component.js (hunk 2 above)
Comment (scotttball) [reply frontend/app/overview/vocabulary/defined-term.component.js]: No reason. I think I was just fooling around a bit. I’ll change the toggles back. There’s an eslint warning for the event function and that’s why I moved it in the useEffect.

Comment (scotttball) [reply frontend/app/overview/vocabulary/defined-term.component.js]: I needed the `openTooltip` in the useEffect so that's why I moved them up. Would you like me change them back to declarations?

Comment (joeldenning) [reply frontend/app/overview/vocabulary/defined-term.component.js]: if they are declarations, they are hoisted and can be used anywhere. This is actually why I usually use `function() {}` instead of `const thing = () => {}`.

I don't really mind if you write your own code to use `const thing = () => {}`, but yeah let's not change all of the existing components to it.

**Comment by joeldenning** [comment]
Just one remaining comment, then let's merge https://github.com/JustUtahCoders/utahexpungements.org/pull/119#discussion_r343513803

File: frontend/app/overview/vocabulary/defined-term.component.js (hunk 2 above)
Comment (scotttball) [reply frontend/app/overview/vocabulary/defined-term.component.js]: Ok! Sounds good.
